language: java
sudo: false

before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "
if [ ${TRAVIS_PULL_REQUEST} = 'false' ];
then 
    mvn clean deploy --batch-mode --settings target/travis/settings.xml; 
else 
    mvn clean verify --batch-mode --settings target/travis/settings.xml;
fi"

jdk:
  - oraclejdk8

# whitelist
branches:
  only:
    - develop

env:
  global:
    - secure: "oeX+TfpSechuJFm0flfd+XCzI4FZeAQGOocjBlyubfzLePPOauJBYNSXBCb0KhDzVbpkVtnqqQw13M1GtNBkDnL1At1W0SOTq4FJDATuaNN+YTFSV9je9861D9bvigA2WuNbTYXqLEmW/TSoYpXSO1CMleVWQfvXp2JTtWSYhLE="
    - secure: "fWv856hCNZecAV9x604L0kx+WuOsgDuN7gYjc8hbf9reJlE2zHSM3/7Ie8NQKsN0SDKG/SqVYehEBhkuAQAUS+b3+LoHd1X7f9cTmhWUygLtDZkPKEKbgQkX50kFPwYEHX8HocUbJAwWNpIY9wocr1kLi0X0XT2VcR20GFAR+Hg="

matrix:
  - LC_ALL=C
  - LC_ALL=pl_PL
  - LC_ALL_zh_CN
